# Generated by Django 4.2.5 on 2023-11-05 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myWeatherApp", "0003_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
