# Generated by Django 4.2.5 on 2023-11-06 01:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myWeatherApp", "0005_userpreference"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WeatherActivity",
            new_name="WeatherGroup",
        ),
    ]
